# Generated by Django 4.1.4 on 2022-12-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instapost',
            name='username',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
